java_test(
    name = "BoardTest",
    srcs = ["BoardTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
        "//java/sublimedisruptors/quoridor/board",
    ],
)

java_test(
    name = "DirectionTest",
    srcs = ["DirectionTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor/board",
    ],
)

java_test(
    name = "GrooveTest",
    srcs = ["GrooveTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor/board",
        "//java/sublimedisruptors/quoridor/testing",
    ],
)

java_test(
    name = "SquareTest",
    srcs = ["SquareTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor/board",
        "//java/sublimedisruptors/quoridor/testing",
    ],
)

java_test(
    name = "VertexTest",
    srcs = ["VertexTest.java"],
    deps = [
        "//java/sublimedisruptors/quoridor/board",
        "//java/sublimedisruptors/quoridor/testing",
    ],
)

java_test(
    name = "WallTest",
    srcs = ["WallTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor/board",
    ],
)
