java_test(
    name = "MoveTest",
    srcs = ["MoveTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
        "//java/sublimedisruptors/quoridor/board",
        "//java/sublimedisruptors/quoridor/move",
        "//java/sublimedisruptors/quoridor/testing",
    ],
)

java_test(
    name = "MoveGeneratorTest",
    srcs = ["MoveGeneratorTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
        "//java/sublimedisruptors/quoridor/board",
        "//java/sublimedisruptors/quoridor/move",
        "//java/sublimedisruptors/quoridor/testing",
    ],
)
