java_test(
    name = "MoveTest",
    size = "small",
    srcs = ["MoveTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
        "//java/sublimedisruptors/quoridor/board",
        "//java/sublimedisruptors/quoridor/move",
        "//java/sublimedisruptors/quoridor/testing",
    ],
)

java_test(
    name = "RulesGovernorTest",
    size = "small",
    srcs = ["RulesGovernorTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
        "//java/sublimedisruptors/quoridor/board",
        "//java/sublimedisruptors/quoridor/move",
        "//java/sublimedisruptors/quoridor/testing",
    ],
)
