package(default_visibility = ["//java/sublimedisruptors/quoridor:quoridor_packages"])

java_library(
    name = "testing",
    testonly = 1,
    srcs = glob(["*.java"]),
    deps = ["//deps:truth"],
)
