java_test(
    name = "EdgeTest",
    srcs = glob(["EdgeTest.java"]),
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
    ],
)

java_test(
    name = "DirectionTest",
    srcs = glob(["DirectionTest.java"]),
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
    ],
)
