java_test(
    name = "DirectionTest",
    srcs = ["DirectionTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
    ],
)

java_test(
    name = "EdgeTest",
    srcs = ["EdgeTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
    ],
)

java_test(
    name = "SquareTest",
    srcs = ["SquareTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
    ],
)

java_test(
    name = "VertexTest",
    srcs = ["VertexTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
    ],
)

java_test(
    name = "WallTest",
    srcs = ["WallTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
    ],
)
