java_test(
    name = "QuoridorSettingsTest",
    srcs = ["QuoridorSettingsTest.java"],
    deps = [
        "//deps:guava",
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
        "//java/sublimedisruptors/quoridor/testing",
    ],
)
