package(default_visibility = ["//java/sublimedisruptors/quoridor:quoridor_packages"])

java_library(
    name = "board",
    srcs = glob(["*.java"]),
    deps = [
        "//deps:auto_value",
        "//deps:guava",
        "//java/sublimedisruptors/quoridor",
    ],
)
