package(default_visibility = ["//java/sublimedisruptors/quoridor:quoridor_packages"])

java_library(
    name = "move",
    srcs = glob(["*.java"]),
    deps = [
        "//deps:auto_value",
        "//deps:guava",
        "//java/sublimedisruptors/quoridor",
        "//java/sublimedisruptors/quoridor/board",
    ],
)
