java_test(
    name = "GameMasterTest",
    size = "small",
    srcs = ["GameMasterTest.java"],
    deps = [
        "//deps:truth",
        "//java/sublimedisruptors/quoridor",
        "//java/sublimedisruptors/quoridor/board",
        "//java/sublimedisruptors/quoridor/move",
        "//java/sublimedisruptors/quoridor/testing",
    ],
)
